build:
  image: node:18
  stage: build
  script:
    - cp example-foundryconfig.json foundryconfig.json
    - npm install
    - npm install --global gulp-cli
    - gulp package
    - mkdir $CI_PROJECT_NAME
    - cp dist/module.json $CI_PROJECT_NAME
    - cp package/$CI_PROJECT_NAME-*.zip $CI_PROJECT_NAME
  artifacts:
    paths:
      - $CI_PROJECT_NAME
    when: always

deploy to s3:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - echo $CI_PROJECT_NAME
    - aws --version
    - aws s3 cp $CI_PROJECT_NAME s3://kristianserrano/foundryvtt/$CI_PROJECT_NAME/$CI_COMMIT_TAG --acl public-read --recursive
    - aws s3 cp "${CI_PROJECT_NAME}/module.json" s3://kristianserrano/foundryvtt/$CI_PROJECT_NAME --acl public-read --recursive
  rules:
  - if: $CI_COMMIT_TAG