workflow:
  script:
  - export
  rules:
  - if: $CI_COMMIT_TAG

build:
  image: node:18
  stage: build
  script:
    - cp example-foundryconfig.json foundryconfig.json
    - npm install
    - npm install --global gulp-cli
    - gulp package
    - mkdir adventure-deck-hands
    - cp package/adventure-deck-hands-*.zip adventure-deck-hands
    - cp dist/module.json adventure-deck-hands
  artifacts:
    paths:
      - adventure-deck-hands
    when: always

deploy to s3:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - aws s3 cp adventure-deck-hands s3://kristianserrano/foundryvtt/adventure-deck-hands --acl public-read --recursive