workflow:
  script:
  - export
  rules:
  - if: $CI_COMMIT_TAG

build:
  image: node:18
  stage: build
  script:
    - cp example-foundryconfig.json foundryconfig.json
    - npm install
    - npm install --global gulp-cli
    - gulp package
    - mkdir swade-card-hands
    - cp package/swade-card-hands-*.zip swade-card-hands
    - cp dist/module.json swade-card-hands
  artifacts:
    paths:
      - swade-card-hands
    when: always

deploy to s3:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - aws s3 cp swade-card-hands s3://kristianserrano/foundryvtt/swade-card-hands --acl public-read --recursive