workflow:
  script:
  - export
  rules:
  - if: $CI_COMMIT_TAG

build:
  image: node:18
  stage: build
  script:
    - cp example-foundryconfig.json foundryconfig.json
    - npm install
    - npm install --global gulp-cli
    - gulp package
    - mkdir card-hands-list
    - cp package/card-hands-list-*.zip card-hands-list
    - cp dist/module.json card-hands-list
    - VERSION=$(node -p "require('dist/module.json').version")
  artifacts:
    paths:
      - card-hands-list
    when: always

deploy to s3:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version
    - aws s3 cp card-hands-list s3://kristianserrano/foundryvtt/card-hands-list/$VERSION --acl public-read --recursive